---
title: "First Knit"
author: " Sandra Iovino "
output: 
  html_document:
    number_sections: true
    toc: true
    toc_depth: 5
date: "`r Sys.Date()`"   



# A Little Survey



Here are just a few questions so I can get to know you and so you can get practice submitting an assignment in Canvas.  For each question, insert your answer underneath. Make sure each answer is at the minimum a complete sentence with correctly spelled words and correct puncuation. 

## A short history of you.  
Where did you attend High School, and did you graduate? Compare english class to math, is one easier for you than the other? Finally which subject did you do the best in? Your answer should have at least two sentences devoted to each question.  
  
### my answer     
  
 I went to Palmdale High School and I did graduate. I prefer math than English. I did very well in math in school. When I went to college I did great in History.  


## Your computer and your and its capability?  
 For this class  you need a computer you can use at home.  So, what kind is it (windows, Apple, Linux)?  On a scale of 1 to 10, where 1 is a total dummy (doesn't know a mouse from a keyboard) and 10 is a complete geek (knows computer stuff in and out) How do you rate yourself?  You also need to have have internet access. How is your connection to the internet where you live?

### my answer   
  
  I have a apple computer. It is very diffrent than HP computer. If I were to rate myslef I would be a 6 because I can fix the issue but it does take me sometime. I have internet access at my house. I am able to get on my computer and due homework. 
   

## Others and You?   
What name do you prefer to be called by your classmates and instructor, if your buddys call you something but you want people in the class to call you something else - what would that be? 

### my answer  

  I would like to be called Sandra or Sandy. I wouldn't mind either one, they are both me. 


## Aspirations?   
What do you want to achieve in life?  What college subject do you think would be of the greatest interest to you? What degree or certificate are you trying to achieve?

### my answer     
  
  Something I would like to achieve in life is become a RN. I want to transfer to CSUN because they have a nice campus for nursing. A subject that is gretatest interest to me is science. I have my AA in Science but I want to get my ADN. 
 




## Past adventures?  
Have you ever gone to foreign countries, if so which ones, if not Where might you go in the future?  Have you ever been in the military, if so which branch, if not which branch would you choose if you got drafted, and why?

### my answer     
  
I have not been to a fereign country. Somewhere I want to go is Guatemala. I have not been in the military. If I where to join the military, I would want to go in the Air force branch. I always loved planes. I like to be in the air and knowing the history of the plane and the equipment they use. 
  




## Why are you taking Statistics?  
Did you take Math 115 or Math 116 ?  Did you know Math 115 only satisfies a general education requirement but that Math 116 counts as taking statistics in several transfer institutions??  
What grade do you need to attain in stats to not upset your future plans, What is your plan?  
 

### my answer     
  
   I have not taken math 115 or math 116. I did not know that math 115 or math 116 counted for statistic in several transfers. The grade I need for this class is an A or B for my future plan. My plan is to turn in all my homework and be in class. 
 






  




